<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:macro name="base" params="length width height mass ">
    
    <link name="base_link">
      <visual>
        <!-- Changed the origin to position the center of the visual box at the front of the robot -->
        <origin xyz="${length/2} 0 ${height/2}" rpy="0 0 3.14"/>
        <geometry>
          <box size="${length} ${width} ${height}"/>
        </geometry>
        <material name="yellow">
          <color rgba="0.8784 0.6627 0.6627 1.0"/>
        </material>
      </visual>
      
      <collision>
        <!-- Updated collision origin to match visual origin -->
        <origin xyz="${length/2} 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="${length} ${width} ${height}"/>
        </geometry>
      </collision>

      <inertial>
        <!-- Updated inertial origin to match the new center of mass -->
        <origin xyz="${length/2} 0 0" rpy="0 0 0"/>
        <mass value="${mass}"/>
        <inertia ixx="${(1/12) * mass * ((width  * width)  + (height * height))}" ixy="0.0" ixz="0.0"
                 iyy="${(1/12) * mass * ((length * length) + (height * height))}" iyz="0.0"
                 izz="${(1/12) * mass * ((length * length) + (width  * width))}"/>
      </inertial>
    </link>

    <gazebo reference="base_link">  
      <visual>  
        <material>
          <ambient>0.8392 0.6314 0.0 1.0</ambient>  
          <diffuse>0.8392 0.6314 0.0 1.0</diffuse>  
          <specular>0.99 0.99 0.99 1.0</specular>  
          <emissive>0.0 0.0 0.0 0.0</emissive>  
        </material>
      </visual> 
    </gazebo>

    <link name="base_footprint"/>

    <joint name="base_to_footprint" type="fixed">
      <parent link="base_footprint"/>
      <child link="base_link"/>
      <!-- Position the base_footprint directly below the front center of the robot -->
      <origin xyz="0 0 ${height/2}" rpy="0 0 0"/>
    </joint>

  </xacro:macro>
</robot>