<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- IMU inertia for box shape -->
    <xacro:macro name="imu_inertial_box" params="mass x y z *origin">
        <inertial>
            <xacro:insert_block name="origin"/>
            <mass value="${mass}" />
            <inertia ixx="${(1/12) * mass * (y*y + z*z)}" ixy="0.0" ixz="0.0"
                    iyy="${(1/12) * mass * (x*x + z*z)}" iyz="0.0"
                    izz="${(1/12) * mass * (x*x + y*y)}" />
        </inertial>
    </xacro:macro>

    <xacro:macro name="imu">
        <!-- IMU Link -->
        <link name="imu_link">
            <visual>
                <geometry>
                    <box size="0.01 0.01 0.01"/>
                </geometry>
                <material name="green">
                    <color rgba="0.0 0.8 0.0 1.0"/>
                </material>
            </visual>
            <collision>
                <geometry>
                    <box size="0.01 0.01 0.01"/>
                </geometry>
            </collision>
            <xacro:imu_inertial_box mass="0.01" x="0.01" y="0.01" z="0.01">
                <origin xyz="0 0 0" rpy="0 0 0"/>
            </xacro:imu_inertial_box>
        </link>

        <!-- IMU Joint (attach to front of the robot) -->
        <joint name="imu_joint" type="fixed">
            <parent link="base_link"/>
            <child link="imu_link"/>
            <origin xyz="${base_length/2 + 0.001} 0 ${base_height/2 + 0.005}" rpy="0 0 0"/>
        </joint>

        <!-- IMU Gazebo plugin -->
        <gazebo reference="imu_link">
            <material>Gazebo/Green</material>
            <sensor name="imu_sensor" type="imu">
                <pose>0 0 0 0 0 0</pose>
                <always_on>false</always_on>
                <update_rate>10</update_rate>
                <visualize>true</visualize>
                <plugin name="imu_plugin" filename="libgazebo_ros_imu_sensor.so">
                    <ros>
                        <namespace>/imu</namespace>
                        <remapping>~/out:=data</remapping>
                    </ros>
                    <initial_orientation_as_reference>false</initial_orientation_as_reference>
                    <frame_name>imu_link</frame_name>
                </plugin>
                <imu>
                    <angular_velocity>
                        <x>
                            <noise type="gaussian">
                                <mean>0.0</mean>
                                <stddev>2e-4</stddev>
                                <bias_mean>0.0000075</bias_mean>
                                <bias_stddev>0.0000008</bias_stddev>
                            </noise>
                        </x>
                        <y>
                            <noise type="gaussian">
                                <mean>0.0</mean>
                                <stddev>2e-4</stddev>
                                <bias_mean>0.0000075</bias_mean>
                                <bias_stddev>0.0000008</bias_stddev>
                            </noise>
                        </y>
                        <z>
                            <noise type="gaussian">
                                <mean>0.0</mean>
                                <stddev>2e-4</stddev>
                                <bias_mean>0.0000075</bias_mean>
                                <bias_stddev>0.0000008</bias_stddev>
                            </noise>
                        </z>
                    </angular_velocity>
                    <linear_acceleration>
                        <x>
                            <noise type="gaussian">
                                <mean>0.0</mean>
                                <stddev>1.7e-2</stddev>
                                <bias_mean>0.1</bias_mean>
                                <bias_stddev>0.001</bias_stddev>
                            </noise>
                        </x>
                        <y>
                            <noise type="gaussian">
                                <mean>0.0</mean>
                                <stddev>1.7e-2</stddev>
                                <bias_mean>0.1</bias_mean>
                                <bias_stddev>0.001</bias_stddev>
                            </noise>
                        </y>
                        <z>
                            <noise type="gaussian">
                                <mean>0.0</mean>
                                <stddev>1.7e-2</stddev>
                                <bias_mean>0.1</bias_mean>
                                <bias_stddev>0.001</bias_stddev>
                            </noise>
                        </z>
                    </linear_acceleration>
                </imu>
            </sensor>
        </gazebo>
    </xacro:macro>
</robot>
