twist_mux:
  ros__parameters:
    topics:
      navigation:
        topic   : /cmd_vel
        timeout : 0.5
        priority: 10
      joystick:
        topic   : /cmd_vel_joy
        timeout : 0.5
        priority: 100
      vlm_control:
        topic   : /cmd_vel_vlm
        timeout : 0.5
        priority: 50