teleop_twist_joy_node:
  ros__parameters:
    axis_linear:
      x: 1  # Left stick vertical axis
    scale_linear:
      x: 0.8
    axis_angular:
      yaw: 2  # Right stick horizontal axis
    scale_angular:
      yaw: 1.0
    enable_button: 7  # LB button
    require_enable_button: true  # Optional enable button
